In [1]:
import h5py
import open3d as o3d
import numpy as np

In [9]:
with h5py.File('shapef.h5', 'r') as hf:
    i = 0
    cloud = np.array(hf['output'][i])
    pcd = o3d.geometry.PointCloud()
    pcd.points = o3d.utility.Vector3dVector(cloud)
    o3d.io.write_point_cloud("datasets/open3d/{}_cloud.ply".format(i), pcd)

[[ 0.03684177  0.03355656 -0.00246312]
 [ 0.03684226  0.03355627 -0.0024633 ]
 [ 0.03684274  0.033556   -0.00246347]
 ...
 [ 0.03687491  0.03356519 -0.00246633]
 [ 0.03687496  0.03356508 -0.00246689]
 [ 0.03687502  0.033565   -0.00246747]]
